# Generated by Django 4.0.3 on 2022-03-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('pic', models.ImageField(upload_to='photos/%Y/%M/%D', verbose_name='Post Picture')),
                ('content', models.CharField(max_length=200, verbose_name='Post Content')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts_related', to='Posts.category')),
            ],
        ),
    ]
