# Generated by Django 4.0.3 on 2022-03-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_category_subbed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts_related', to='Posts.category'),
        ),
    ]
