# Generated by Django 4.0.3 on 2022-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=20000, verbose_name='Post Content'),
        ),
    ]
