# Generated by Django 4.0.3 on 2022-03-18 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0004_postlikes_postdislikes'),
        ('Comments', '0002_blockedwords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedWords',
            new_name='BlockedWord',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
